### ISSUE TITLE
希望加入typescript支持啊

### ISSUE THREAD

**Issue by cnjack** [xiaoyao96/wxMiniStore#10]
如题

**Comment by chris-fung** [comment]
严重支持

**Comment by yx675258207** [comment]
ts本身是支持js的，只需用require函数引入即可。
所以将github下的lib/store.js放入原生ts小程序项目下的miniprogram下的任意目录内，在app.ts中通过require引入，如：
``` js
const Store = require('./utils/store.js');
new Store({
    state: {
        a: 1
    }
});
```
忙着搞公司的项目，所以回复的慢见谅..

**Comment by yx675258207** [comment]
后续会加上d.ts，刚才试了下，ts原生小程序npm构建不了...有点奇怪。

**Comment by cnjack** [comment]
可以的 你需要编译一下 并且允许npm

**Comment by yx675258207** [comment]
> 可以的 你需要编译一下 并且允许npm

构建的时候提示，没有找到可以构建的npm包。js原生小程序没这个问题...

**Comment by yx675258207** [comment]
> 可以的 你需要编译一下 并且允许npm

找到了... 在 miniprogram 目录下进行安装就可以了。require('wxministore')

**Comment by cnjack** [comment]
哈哈 对的
