### ISSUE TITLE
在new Store({state:{   },methods:{  })中，methods中的方法无法改变state 中的属性值，这个问题如何解决

### ISSUE THREAD

**Issue by wumingwei** [xiaoyao96/wxMiniStore#14]
#### 登录的状态，token,与登录刷新token的方法，需要在页面里面调用登录，刷新token等逻辑的方法，目前关于token,登录态的处理是在页面方法的回调中改变的state中的相关token与登录态，当；逻辑比较复杂时，维护比较困难。代码如下：
```javascript
// store.js
let store = new Store({
  state:{
     token:"",
     hasLogin:false,
   },
   methods:{
       // 刷新token
     refreshToken(token){
       //  ......
       // 无法直接设置state中的token
     },
   }
})
```
#### 请问可以支持以上的设置吗？

**Comment by wumingwei** [comment]
### 业务场景：
#### 登录的状态，token,与登录刷新token的方法，需要在页面里面调用登录，刷新token等逻辑的方法，目前关于token,登录态的处理是在页面方法的回调中改变的state中的相关token与登录态，当；逻辑比较复杂时，维护比较困难。代码如下：
```javascript
// store.js
let store = new Store({
  state:{
     token:"",
     hasLogin:false,
   },
   methods:{
       // 刷新token
     refreshToken(token){
       //  ......
       // 无法直接设置state中的token
     },
   }
})
```
#### 请问可以支持以上的设置吗？

**Comment by yx675258207** [comment]
从你代码上来看，这个是本身支持的。任何地方store.setState都可更新state。

**Comment by arden** [comment]
这个状态管理器和直接使用globaldata有什么优势？

**Comment by yx675258207** [comment]
> 这个状态管理器和直接使用globaldata有什么优势？

globaldata 是数据管理，没有更新视图的能力。本状态管理是 数据管理 驱动 视图更新。 类似于vuex。
