### ISSUE TITLE
首次下载小程序包,在小程序直播插件分包内调用单独的request.js  getCurrentPages拿不到store内methods的方法

### ISSUE THREAD

**Issue by CCdingxin** [xiaoyao96/wxMiniStore#17]
复现场景
用户为第一次下载小程序,进入小程序直播分包内,app.js调用request.js请求
返回结果后使用getCurrentPages().pop()为空  拿不到store methods内的方法
app.js内onLaunch和onShow第一时间拿不到getCurrentPages().pop()内方法需要加延时
其他情况是可以拿到的  在非page和components内还有其他方法可以拿到methods方法么
有什么方法可以兼容一下么  还是我的打开方式不对😂

**Comment by xiaoyao96** [comment]
methods一般是用于wxml里的事件行为。如果是公共函数放App里注册，而不是store里。

**Comment by xiaoyao96** [comment]
然后回到你的问题上，官方文档有解释：
`不要在 App.onLaunch 的时候调用 getCurrentPages()，此时 page 还没有生成。`
https://developers.weixin.qq.com/miniprogram/dev/reference/api/getCurrentPages.html

至于你问题的解决方案可以新建一个js。目录为util/index.js
```js
// util/index.js
export function f1(){}
export function f2(){}

// app.js
import { f1 } from '/utils.js'

App({
    onLauch(){
          f1();
    }
})
```

**Comment by zkl2333** [comment]
不要在`App.onLaunch`的时候用调`getCurrentPages()`和`getApp()`。哈哈哈哈我也坑过

**Comment by xiaoyao96** [comment]
> 不要在`App.onLaunch`的时候用调`getCurrentPages()`和`getApp()`。哈哈哈哈我也坑过

面向文档编程就好，文档没有才是坑。
