### ISSUE TITLE
关于“diff后实际设置的值”在控制台中的显示

### ISSUE THREAD

**Issue by zkl2333** [xiaoyao96/wxMiniStore#22]
建议加个可选的配置项控制是否显示调试信息。
这一点我觉得[omix](https://github.com/Tencent/omi/tree/master/packages/omix)做的不错。

**Comment by xiaoyao96** [comment]
> 建议加个可选的配置项控制是否显示调试信息。
> 这一点我觉得[omix](https://github.com/Tencent/omi/tree/master/packages/omix)做的不错。

ok，可以安排
