### ISSUE TITLE
关于 onShareAppMessage 是采用 pageListener 会失去图片

### ISSUE THREAD

**Issue by Rattenking** [xiaoyao96/wxMiniStore#31]
由于 onShareAppMessage 、 onReachBottom 、onPullDownRefresh等是触发性事件函数，所以不能归类为生命周期，也就是说，不能直接 pageListener[key].apply(this, arguments)；对于触发性事件函数，我建议单独归类，同时采用赋值 o[key] = pageListener[key]，但是有个前提就是 o[key]无效，才采用公用的。建议下个版本修改一下！

生命周期是直接执行，所以能够 pageListener[key].apply(this, arguments)，触发事件不会直接执行，所以必须采用赋值，等到触发时执行！

官网解释：
https://developers.weixin.qq.com/miniprogram/dev/reference/api/Page.html#onshareappmessageobject-object

**Comment by xiaoyao96** [comment]
关于onShareAppMessage的解决方案，可以看下 #7 中我的答复哦~

pageListener职责是为了监听，也就是说不会覆盖原页面里的周期逻辑，同时也会执行监听。

pageListener里的函数采用的装饰器模式，在注册页面阶段（Page函数执行完成）时就已经装饰完成所有页面里对应的函数了。

pageLisener里的函数都不是主动触发的，原理里只是覆盖了原有Page里的函数，做了一层装饰，所以不存在你说的那些问题哦！

希望能解决你的问题哦~

**Comment by Rattenking** [comment]
> 关于onShareAppMessage的解决方案，可以看下 #7 中我的答复哦~
> 
> pageListener职责是为了监听，也就是说不会覆盖原页面里的周期逻辑，同时也会执行监听。
> 
> pageListener里的函数采用的装饰器模式，在注册页面阶段（Page函数执行完成）时就已经装饰完成所有页面里对应的函数了。
> 
> pageLisener里的函数都不是主动触发的，原理里只是覆盖了原有Page里的函数，做了一层装饰，所以不存在你说的那些问题哦！
> 
> 希望能解决你的问题哦~

你源码：
const pageLife = [
      "data",
      "onLoad",
      "onShow",
      "onReady",
      "onHide",
      "onUnload",
      "onPullDownRefresh",
      "onReachBottom",
      "onShareAppMessage",
      "onPageScroll",
      "onTabItemTap",
    ];
重写生命周期：
Object.keys(pageListener).forEach((key) => {
        //不能是周期事件
        if (
          typeof pageListener[key] === "function" &&
          pageLife.some((item) => item === key)
        ) {
          const originLife = o[key];
          o[key] = function () {
            pageListener[key].apply(this, arguments);
            originLife && originLife.apply(this, arguments);
          };
        }
      });
你可测试在全局执行onReachBottom监听，你会发现你的插件，在进入就会执行一次onReachBottom，但事实就是开发中进入页面，onReachBottom不会一开始就执行，只有滚动到底部才执行。不过一般也不会在全局监听 onReachBottom ，所以问题对于大多说人来说也不大！

**Comment by xiaoyao96** [comment]
我测试发现并没有自动执行pageListener的onReachBottom。

应该是你的页面渲染过程中，回流导致滚动条触底，间接导致onReachBottom触发。

所以可以在你触发的页面里加上onReachBottom应该也会执行。

源码里的采用的装饰器模式，是不会执行的...

o[key] = function () {
....
};

这里是声明一个函数...

**Comment by Rattenking** [comment]
> 我测试发现并没有自动执行pageListener的onReachBottom。
> 
> 应该是你的页面渲染过程中，回流导致滚动条触底，间接导致onReachBottom触发。
> 
> 所以可以在你触发的页面里加上onReachBottom应该也会执行。
> 
> 源码里的采用的装饰器模式，是不会执行的...
> 
> o[key] = function () {
> ....
> };
> 
> 这里是声明一个函数...

试试onShareAppMessage，获取参数这些都是正常的，但是imageUrl丢失了，即便图片写死。我测试了好几次。

**Comment by xiaoyao96** [comment]
onShareAppMessage 暂时不要写在PageLisenter里，这个bug是因为覆盖了原 onShareAppMessage，导致页面里的分享没有返回值。所以解决方案可以先使用 #7 。我下个版本修复返回值的问题，应该今天会发一版

**Comment by Rattenking** [comment]
> onShareAppMessage 暂时不要写在PageLisenter里，这个bug是因为覆盖了原 onShareAppMessage，导致页面里的分享没有返回值。所以解决方案可以先使用 #7 。我下个版本修复返回值的问题，应该今天会发一版

好的，谢谢！

**Comment by Rattenking** [comment]
问题已解决！

**Comment by xiaoyao96** [comment]
> 问题已解决！

ok的，我刚测试完成新的想法，可以写在pageListener的解决方案，待会发布1.3.1可以尝试一下。

**Comment by xiaoyao96** [comment]
1.3.1已更新，之前你的写法已支持。

**Comment by Rattenking** [comment]
> 1.3.1已更新，之前你的写法已支持。

好的，我一看到你源码解决了。我咨询一个问题，new Proxy为什么监听不到小程序this.setData修改，只能监听this.data修改？

**Comment by xiaoyao96** [comment]
> > 1.3.1已更新，之前你的写法已支持。
> 
> 好的，我已看到你源码解决了。我咨询一个问题，new Proxy为什么监听不到小程序this.setData修改，只能监听this.data修改？

你是怎么监听的 this.data 。在初始化Page时，data会被深拷贝。按理来说是无法利用Porxy监听data的变化的。
