### ISSUE TITLE
小程序代码转taro时 初始化报错

### ISSUE THREAD

**Issue by tayen520** [xiaoyao96/wxMiniStore#34]
![2021-06-17 12-03-42屏幕截图](https://user-images.githubusercontent.com/59039957/122329652-5d10e680-cf64-11eb-951e-80be72a33b3d.png)
![2021-06-17 12-04-25屏幕截图](https://user-images.githubusercontent.com/59039957/122329662-60a46d80-cf64-11eb-85d0-20723c8403cb.png)

**Comment by tayen520** [comment]
上面的报错我改成es6导出显示的错误，如果用您的es5导出会报下面的错误
![2021-06-17 14-44-23屏幕截图](https://user-images.githubusercontent.com/59039957/122345594-9a806e80-cf7a-11eb-901e-30ffe4a05ec2.png)
![2021-06-17 14-44-54屏幕截图](https://user-images.githubusercontent.com/59039957/122345599-9ce2c880-cf7a-11eb-8554-01f18104b3d0.png)

**Comment by xiaoyao96** [comment]
暂不支持转Taro，
只能使用mobx或者redux进行管理全局状态。
