### ISSUE TITLE
小程序的异步机制导致store获取数据为空，如何处理

### ISSUE THREAD

**Issue by zhixu369** [xiaoyao96/wxMiniStore#36]
在App.js的onLaunch中请求后台api获取用户信息，然后保存到store中
然后在首页onLoad中从store中获取用户信息，结果是空
我知道这是由于异步导致的，如何在页面中监听到store中有值了，然后获取值，并且渲染到页面中

**Comment by xiaoyao96** [comment]
store会自动挂载state到页面的data里，按理是不需要在首页去接收值的。如果你确实需要这样，可以用Promise实现，在App.js的onLaunch内用this.promise = new Promise 去请求。在首页onLoad中使用this.promise.then去接收，
```js
App({
   onLaunch(){
       this.promise = new Promise((resolve) => {
             // 请求
             resolve(结果)
       })
   }
})
```
页面中
```
Page({
    onLoad(){
        getApp().promise.then(result => {
           // TODO 你要做的事
        })
    }
})
