### ISSUE TITLE
pageListener 中，不能监听 onThemeChange

### ISSUE THREAD

**Issue by iZaiZaiA** [xiaoyao96/wxMiniStore#37]
onThemeChange(Object object)
基础库 2.11.0 开始支持，低版本需做兼容处理。

系统切换主题时触发。也可以使用 wx.onThemeChange 绑定监听。

参数：与 wx.onThemeChange 一致

https://developers.weixin.qq.com/miniprogram/dev/reference/api/App.html#onThemeChange-Object-object

**Comment by xiaoyao96** [comment]
pageListener用于解决重复监听Page级的一些行为，比如onLoad、onShareAppMessage等，如果没有pageListener，你可能需要每个页面去注册这些重复的工作。 onThemeChange本来只存在于App.js中，故pageListener并不需要
